- hosts: "{{ passed_in_hosts }}"
  become: true
  tasks:
    - name: Copy SSH private key to remote machine
      copy:
        src: /var/lib/jenkins/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600
    - name: Copy SSH private key to remote machine ubuntu
      copy:
        src: /var/lib/jenkins/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Copy SSH public key to authorized_keys
      copy:
        src: /var/lib/jenkins/.ssh/id_rsa.pub
        dest: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: 0600

    - name: Copy SSH public key to authorized_keys ubuntu
      copy:
        src: /var/lib/jenkins/.ssh/id_rsa.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        owner: ubuntu
        group: ubuntu
        mode: 0600
